import { Product } from "./types";

export const seedProducts: Product[] = [
  {
    id: "p-1001",
    manufacturerId: "1",
    manufacturerName: "ABC",
    name: "Aurora Wireless Headphones",
    sku: "ELEC-AWH-01",
    category: "Electronics",
    description:
      "Over-ear noise cancelling headphones with 40h battery life and USB-C fast charging.",
    price: 149.99,
    cost: 82.0,
    quantity: 132,
    reorderLevel: 25,
    status: "active",
    images: [],
    createdAt: "2026-01-12T09:30:00.000Z",
  },
  {
    id: "p-1002",
    manufacturerId: "2",
    manufacturerName: "BCD",
    name: "Terra Stainless Water Bottle",
    sku: "HOME-TSB-22",
    category: "Home & Kitchen",
    description: "Insulated 750ml bottle keeping drinks cold for 24h and hot for 12h.",
    price: 24.5,
    cost: 9.75,
    quantity: 18,
    reorderLevel: 30,
    status: "active",
    images: [],
    createdAt: "2026-02-03T14:10:00.000Z",
  },
  {
    id: "p-1003",
    manufacturerId: "3",
    manufacturerName: "CDE",
    name: "Vertex Running Shoes",
    sku: "SPRT-VRS-09",
    category: "Sports",
    description: "Lightweight breathable mesh runners with responsive foam midsole.",
    price: 89.0,
    cost: 41.2,
    quantity: 0,
    reorderLevel: 15,
    status: "active",
    images: [],
    createdAt: "2026-02-21T11:45:00.000Z",
  },
  {
    id: "p-1004",
    manufacturerId: "4",
    manufacturerName: "DEF",
    name: "Lumen Desk Lamp",
    sku: "OFFC-LDL-14",
    category: "Office",
    description: "Dimmable LED desk lamp with wireless charging base and 3 color modes.",
    price: 59.99,
    cost: 27.5,
    quantity: 64,
    reorderLevel: 20,
    status: "active",
    images: [],
    createdAt: "2026-03-08T16:20:00.000Z",
  },
  {
    id: "p-1005",
    manufacturerId: "5",
    manufacturerName: "EFI",
    name: "Cloud Cotton T-Shirt",
    sku: "APRL-CCT-07",
    category: "Apparel",
    description: "Premium combed cotton crew-neck tee, pre-shrunk and tagless.",
    price: 19.99,
    cost: 6.4,
    quantity: 240,
    reorderLevel: 50,
    status: "active",
    images: [],
    createdAt: "2026-03-19T08:05:00.000Z",
  },
  {
    id: "p-1006",
    manufacturerId: "1",
    manufacturerName: "ABC",
    name: "Glow Vitamin C Serum",
    sku: "BEUT-GVS-03",
    category: "Beauty",
    description: "Brightening 20% vitamin C serum with hyaluronic acid, 30ml.",
    price: 34.0,
    cost: 11.9,
    quantity: 9,
    reorderLevel: 12,
    status: "draft",
    images: [],
    createdAt: "2026-04-02T13:00:00.000Z",
  },
  {
    id: "p-1007",
    manufacturerId: "2",
    manufacturerName: "BCD",
    name: "PixelPlay Building Blocks",
    sku: "TOYS-PBB-18",
    category: "Toys",
    description: "500-piece creative building block set compatible with major brands.",
    price: 42.5,
    cost: 18.0,
    quantity: 76,
    reorderLevel: 20,
    status: "active",
    images: [],
    createdAt: "2026-04-15T10:30:00.000Z",
  },
  {
    id: "p-1008",
    manufacturerId: "3",
    manufacturerName: "CDE",
    name: "Nimbus Bluetooth Speaker",
    sku: "ELEC-NBS-05",
    category: "Electronics",
    description: "Compact waterproof speaker with 360° sound and 16h playtime.",
    price: 69.99,
    cost: 30.0,
    quantity: 21,
    reorderLevel: 25,
    status: "archived",
    images: [],
    createdAt: "2026-04-28T17:40:00.000Z",
  },
];
